DROP TABLE IF EXISTS `secrets`;

CREATE TABLE IF NOT EXISTS `secrets` (
  `id` INT(20) AUTO_INCREMENT,
  `access_token` VARCHAR(20) NOT NULL,
  `client_id` VARCHAR(20) NOT NULL,
  `scope` VARCHAR(20) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON
  UPDATE
    CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
) DEFAULT CHARSET = utf8 COLLATE = utf8_bin;